//! `setup-mixxx-musicindex` keeps an existing event (reserved safety task 003)
//! and writes the display output (reserved safety task 004).
//!
//! Each test runs the helper with stub programs, a temporary configuration
//! home, a temporary runtime directory and a stub card directory. Most tests
//! pass `--no-start`. A stub `systemctl` on `PATH` records each call, so a
//! test can never reach the real user manager. The stub publisher gives
//! `config show` to the real publisher binary, so the helper reads the real
//! JSON format.

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::{PermissionsExt, symlink};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use anyhow::{Context, Result};
use tempfile::TempDir;

const MARKER: &str = "# Generated by setup-mixxx-musicindex.sh";
const PLACEHOLDER: &str = "replace-with-provisioned-event-guid";
const PUBLISHER_UNIT_NAME: &str = "musicindex-live-publisher@mixxx.service";
const PRODUCER_UNIT_NAME: &str = "mixxx-now-playing.service";

/// One isolated run environment for the setup helper.
struct Helper {
    root: TempDir,
}

impl Helper {
    fn new() -> Result<Self> {
        let root = tempfile::tempdir()?;
        let helper = Self { root };
        for dir in ["config", "runtime", "home", "asound", "bin"] {
            fs::create_dir_all(helper.path(dir))?;
        }
        symlink("card31", helper.path("asound").join("V4V"))?;
        let publisher_log = helper.publisher_log();
        let systemctl_log = helper.systemctl_log();
        helper.write_stub(
            "musicindex-live-publisher",
            &format!(
                r#"#!/bin/sh
printf '%s\n' "$*" >> '{log}'
if [ "$1" = config ] && [ "$2" = show ]; then
  exec '{real}' "$@"
fi
if [ "$1" = provision ]; then
  token_file=
  while [ $# -gt 0 ]; do
    case "$1" in
      --token-file) token_file=$2; shift 2 ;;
      *) shift ;;
    esac
  done
  printf 'stub-token\n' > "$token_file"
  echo 'Live item provisioned.'
  echo 'The broadcaster token was returned exactly once and cannot be recovered by the relay.'
  echo "Token written to $token_file"
  echo
  echo '[[target]]'
  echo 'name = "default"'
  echo 'event_id = "stub-event"'
  echo "token_file = \"$token_file\""
fi
"#,
                log = publisher_log.display(),
                real = env!("CARGO_BIN_EXE_musicindex-live-publisher"),
            ),
        )?;
        helper.write_stub("mixxx-now-playing", "#!/bin/sh\nexit 0\n")?;
        helper.write_stub(
            "systemctl",
            &format!(
                "#!/bin/sh\nprintf '%s\\n' \"$*\" >> '{}'\nexit 0\n",
                systemctl_log.display()
            ),
        )?;
        Ok(helper)
    }

    fn path(&self, name: &str) -> PathBuf {
        self.root.path().join(name)
    }

    fn write_stub(&self, name: &str, body: &str) -> Result<()> {
        let path = self.path("bin").join(name);
        fs::write(&path, body)?;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
        Ok(())
    }

    fn publisher_log(&self) -> PathBuf {
        self.path("publisher.log")
    }

    fn systemctl_log(&self) -> PathBuf {
        self.path("systemctl.log")
    }

    fn state_dir(&self) -> PathBuf {
        self.path("config").join("musicindex-live-publisher/mixxx")
    }

    fn config_file(&self) -> PathBuf {
        self.state_dir().join("config.toml")
    }

    fn token_dir(&self) -> PathBuf {
        self.state_dir().join("tokens")
    }

    fn unit_dir(&self) -> PathBuf {
        self.path("config").join("systemd/user")
    }

    fn publisher_unit(&self) -> PathBuf {
        self.unit_dir()
            .join("musicindex-live-publisher@mixxx.service")
    }

    fn producer_unit(&self) -> PathBuf {
        self.unit_dir().join("mixxx-now-playing.service")
    }

    fn write_config(&self, event_id: &str) -> Result<String> {
        self.write_config_with_display(event_id, None)
    }

    /// A config with one target `default`, and `display_dir` when given.
    fn write_config_with_display(
        &self,
        event_id: &str,
        display_dir: Option<&Path>,
    ) -> Result<String> {
        fs::create_dir_all(self.token_dir())?;
        let mut text = format!(
            "{MARKER}\n\
             watch_dir = \"/run/user/0/musicindex-live-publisher/mixxx/nowplaying\"\n\
             endpoint = \"https://relay.invalid\"\n\
             \n\
             [[target]]\n\
             name = \"default\"\n\
             event_id = \"{event_id}\"\n\
             token_file = \"{}\"\n",
            self.path("home").join("reserved.token").display()
        );
        if let Some(dir) = display_dir {
            text.push_str(&format!("display_dir = \"{}\"\n", dir.display()));
        }
        fs::write(self.config_file(), &text)?;
        Ok(text)
    }

    /// The directory that the helper names for the display output.
    fn display_dir(&self) -> PathBuf {
        self.path("runtime")
            .join("musicindex-live-publisher/mixxx/display")
    }

    /// The drop directory that the helper names.
    fn watch_dir(&self) -> PathBuf {
        self.path("runtime")
            .join("musicindex-live-publisher/mixxx/nowplaying")
    }

    fn write_old_units(&self) -> Result<()> {
        fs::create_dir_all(self.unit_dir())?;
        fs::write(
            self.publisher_unit(),
            format!("{MARKER}\n[Service]\nExecStart=/old/publisher\n"),
        )?;
        fs::write(
            self.producer_unit(),
            format!("{MARKER}\n[Service]\nPrivateDevices=true\n"),
        )?;
        Ok(())
    }

    fn run(&self, args: &[&str]) -> Result<Output> {
        let mut all = vec!["--no-start"];
        all.extend_from_slice(args);
        self.run_started(&all)
    }

    /// A run without the implicit `--no-start`. The stub `systemctl` records
    /// each call.
    fn run_started(&self, args: &[&str]) -> Result<Output> {
        let script =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("scripts/setup-mixxx-musicindex.sh");
        let bin = self.path("bin");
        let output = Command::new("/bin/bash")
            .arg(script)
            .args(args)
            .env_clear()
            .env("PATH", format!("{}:/usr/bin:/bin", bin.display()))
            .env("HOME", self.path("home"))
            .env("XDG_CONFIG_HOME", self.path("config"))
            .env("XDG_RUNTIME_DIR", self.path("runtime"))
            .env("MUSICINDEX_ASOUND_DIR", self.path("asound"))
            .env("MUSICINDEX_ENDPOINT", "http://127.0.0.1:9")
            .env(
                "MUSICINDEX_LIVE_PUBLISHER_BIN",
                bin.join("musicindex-live-publisher"),
            )
            .env("MIXXX_NOW_PLAYING_BIN", bin.join("mixxx-now-playing"))
            .output()
            .context("run the setup helper")?;
        Ok(output)
    }

    fn publisher_calls(&self) -> Vec<String> {
        read_lines(&self.publisher_log())
    }

    fn systemctl_calls(&self) -> Vec<String> {
        read_lines(&self.systemctl_log())
    }

    fn config_backups(&self) -> Result<Vec<PathBuf>> {
        let mut backups = Vec::new();
        for entry in fs::read_dir(self.state_dir())? {
            let path = entry?.path();
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if name.starts_with("config.toml.bak.") {
                backups.push(path);
            }
        }
        Ok(backups)
    }
}

fn read_lines(path: &Path) -> Vec<String> {
    fs::read_to_string(path)
        .map(|text| text.lines().map(str::to_owned).collect())
        .unwrap_or_default()
}

/// The name, the link target or the content of each entry in a directory.
fn snapshot(dir: &Path) -> Result<BTreeMap<String, String>> {
    let mut entries = BTreeMap::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let value = match fs::read_link(&path) {
            Ok(target) => format!("link:{}", target.display()),
            Err(_) => fs::read_to_string(&path)?,
        };
        entries.insert(name, value);
    }
    Ok(entries)
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

#[test]
fn a_real_event_stops_the_helper_without_force() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;

    let output = helper.run(&[])?;

    assert!(!output.status.success(), "the helper must stop");
    let message = stderr(&output);
    assert!(message.contains("reserved-event"), "{message}");
    assert!(message.contains("No relay request ran"), "{message}");
    assert!(message.contains("--units-only"), "{message}");
    assert_eq!(fs::read_to_string(helper.config_file())?, before);
    assert!(helper.config_backups()?.is_empty());
    assert!(helper.publisher_calls().is_empty());
    assert!(!helper.publisher_unit().exists());
    assert!(!helper.producer_unit().exists());
    Ok(())
}

#[test]
fn force_backs_up_a_real_event_config_and_provisions() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;

    let output = helper.run(&["--force"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let backups = helper.config_backups()?;
    assert_eq!(backups.len(), 1, "one config backup");
    assert_eq!(fs::read_to_string(&backups[0])?, before);
    let calls = helper.publisher_calls();
    assert_eq!(calls.len(), 1, "{calls:?}");
    assert!(calls[0].starts_with("provision "), "{calls:?}");
    let config = fs::read_to_string(helper.config_file())?;
    assert!(config.contains("event_id = \"stub-event\""), "{config}");
    Ok(())
}

#[test]
fn a_placeholder_config_provisions_without_force() -> Result<()> {
    let helper = Helper::new()?;
    helper.write_config(PLACEHOLDER)?;

    let output = helper.run(&[])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let calls = helper.publisher_calls();
    assert_eq!(calls.len(), 1, "{calls:?}");
    assert!(calls[0].starts_with("provision "), "{calls:?}");
    let config = fs::read_to_string(helper.config_file())?;
    assert!(config.contains("event_id = \"stub-event\""), "{config}");
    assert!(!config.contains(PLACEHOLDER), "{config}");
    Ok(())
}

#[test]
fn a_fresh_run_provisions_and_no_start_runs_no_systemctl() -> Result<()> {
    let helper = Helper::new()?;

    let output = helper.run(&[])?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(helper.publisher_calls().len(), 1);
    assert!(helper.token_dir().join("default.token").exists());
    assert!(helper.publisher_unit().exists());
    assert!(helper.producer_unit().exists());
    assert!(
        helper.systemctl_calls().is_empty(),
        "{:?}",
        helper.systemctl_calls()
    );
    Ok(())
}

#[test]
fn a_token_link_that_points_nowhere_stops_the_helper() -> Result<()> {
    let helper = Helper::new()?;
    fs::create_dir_all(helper.token_dir())?;
    let token = helper.token_dir().join("default.token");
    symlink(helper.path("home").join("missing.token"), &token)?;

    let output = helper.run(&[])?;

    assert!(!output.status.success(), "the helper must stop");
    assert!(
        stderr(&output).contains("existing token"),
        "{}",
        stderr(&output)
    );
    assert!(helper.publisher_calls().is_empty());
    assert!(fs::symlink_metadata(&token)?.file_type().is_symlink());
    assert!(!helper.config_file().exists());
    Ok(())
}

#[test]
fn units_only_writes_the_units_and_nothing_else() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;
    fs::write(helper.token_dir().join("default.token"), "kept-token\n")?;
    fs::write(helper.token_dir().join("other.token"), "other-token\n")?;
    symlink("/nowhere", helper.token_dir().join("linked.token"))?;
    let tokens_before = snapshot(&helper.token_dir())?;
    helper.write_old_units()?;

    let output = helper.run(&["--units-only"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(fs::read_to_string(helper.config_file())?, before);
    assert!(helper.config_backups()?.is_empty());
    assert_eq!(snapshot(&helper.token_dir())?, tokens_before);
    // Reserved safety task 004: --units-only reads the config with
    // `config show --json`. It runs no other publisher command.
    let calls = helper.publisher_calls();
    assert_eq!(calls.len(), 1, "{calls:?}");
    assert!(calls[0].starts_with("config show "), "{calls:?}");
    assert!(
        helper.systemctl_calls().is_empty(),
        "{:?}",
        helper.systemctl_calls()
    );

    let producer = fs::read_to_string(helper.producer_unit())?;
    assert!(producer.contains("PrivateDevices=false"), "{producer}");
    let publisher = fs::read_to_string(helper.publisher_unit())?;
    assert!(
        publisher.contains(&format!("--config {}", helper.config_file().display())),
        "{publisher}"
    );
    let unit_names: Vec<String> = snapshot(&helper.unit_dir())?.into_keys().collect();
    for unit in [
        "musicindex-live-publisher@mixxx.service",
        "mixxx-now-playing.service",
    ] {
        assert!(
            unit_names
                .iter()
                .any(|name| name.starts_with(&format!("{unit}.bak."))),
            "no backup of {unit}: {unit_names:?}"
        );
    }
    Ok(())
}

#[test]
fn units_only_without_a_config_stops() -> Result<()> {
    let helper = Helper::new()?;

    let output = helper.run(&["--units-only"])?;

    assert!(!output.status.success(), "the helper must stop");
    assert!(stderr(&output).contains("--units-only needs an existing config"));
    assert!(helper.publisher_calls().is_empty());
    assert!(helper.systemctl_calls().is_empty());
    assert!(!helper.publisher_unit().exists());
    assert!(!helper.producer_unit().exists());
    assert!(!helper.state_dir().exists());
    Ok(())
}

#[test]
fn units_only_checks_the_card() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;
    fs::remove_file(helper.path("asound").join("V4V"))?;

    let output = helper.run(&["--units-only"])?;

    assert!(!output.status.success(), "the helper must stop");
    assert!(
        stderr(&output).contains("MIDI card is missing"),
        "{}",
        stderr(&output)
    );
    assert_eq!(fs::read_to_string(helper.config_file())?, before);
    assert!(!helper.publisher_unit().exists());
    Ok(())
}

/// The name and the content of each entry below a directory, with the
/// entries of each subdirectory.
fn snapshot_tree(dir: &Path) -> Result<BTreeMap<String, String>> {
    let mut entries = BTreeMap::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        if fs::symlink_metadata(&path)?.is_dir() {
            for (inner, value) in snapshot_tree(&path)? {
                entries.insert(format!("{name}/{inner}"), value);
            }
            entries.insert(format!("{name}/"), String::new());
        } else {
            let value = match fs::read_link(&path) {
                Ok(target) => format!("link:{}", target.display()),
                Err(_) => fs::read_to_string(&path)?,
            };
            entries.insert(name, value);
        }
    }
    Ok(entries)
}

fn display_runtime_line() -> &'static str {
    "RuntimeDirectory=musicindex-live-publisher/mixxx/nowplaying \
     musicindex-live-publisher/mixxx/display"
}

fn assert_display_output(producer: &str, display_dir: &Path) {
    let exec_start = producer
        .lines()
        .find(|line| line.starts_with("ExecStart="))
        .unwrap_or_default();
    assert!(
        exec_start.ends_with(&format!(" --display-dir {}", display_dir.display())),
        "{producer}"
    );
    assert!(
        producer.lines().any(|line| line == display_runtime_line()),
        "{producer}"
    );
}

#[test]
fn display_with_a_new_config_writes_the_display_output() -> Result<()> {
    let helper = Helper::new()?;

    let output = helper.run(&["--display"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let config = fs::read_to_string(helper.config_file())?;
    let line = format!("display_dir = \"{}\"", helper.display_dir().display());
    assert!(config.lines().any(|text| text == line), "{config}");
    let producer = fs::read_to_string(helper.producer_unit())?;
    assert_display_output(&producer, &helper.display_dir());
    let publisher = fs::read_to_string(helper.publisher_unit())?;
    assert!(!publisher.contains("display"), "{publisher}");

    // The real publisher reads the written config and shows display_dir.
    let shown = Command::new(env!("CARGO_BIN_EXE_musicindex-live-publisher"))
        .args(["config", "show", "--json", "--config"])
        .arg(helper.config_file())
        .output()?;
    assert!(shown.status.success(), "{}", stderr(&shown));
    let json: serde_json::Value = serde_json::from_slice(&shown.stdout)?;
    assert_eq!(
        json["targets"][0]["display_dir"],
        serde_json::Value::String(helper.display_dir().display().to_string())
    );
    Ok(())
}

#[test]
fn no_display_writes_no_display_line() -> Result<()> {
    let helper = Helper::new()?;

    let output = helper.run(&[])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let config = fs::read_to_string(helper.config_file())?;
    assert!(!config.contains("display"), "{config}");
    for unit in [helper.publisher_unit(), helper.producer_unit()] {
        let text = fs::read_to_string(&unit)?;
        assert!(!text.contains("display"), "{text}");
        assert!(
            text.lines()
                .any(|line| line == "RuntimeDirectory=musicindex-live-publisher/mixxx/nowplaying"),
            "{text}"
        );
    }
    Ok(())
}

#[test]
fn units_only_keeps_the_display_output_of_the_config() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config_with_display("reserved-event", Some(&helper.display_dir()))?;
    helper.write_old_units()?;

    let output = helper.run(&["--units-only"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(fs::read_to_string(helper.config_file())?, before);
    let producer = fs::read_to_string(helper.producer_unit())?;
    assert_display_output(&producer, &helper.display_dir());
    let calls = helper.publisher_calls();
    assert_eq!(calls.len(), 1, "{calls:?}");
    assert!(
        calls[0].starts_with("config show ") && calls[0].contains("--json"),
        "{calls:?}"
    );
    Ok(())
}

#[test]
fn units_only_display_without_display_dir_stops_and_writes_nothing() -> Result<()> {
    let helper = Helper::new()?;
    helper.write_config("reserved-event")?;
    helper.write_old_units()?;
    let units_before = snapshot(&helper.unit_dir())?;
    let state_before = snapshot_tree(&helper.state_dir())?;

    let output = helper.run(&["--units-only", "--display"])?;

    assert!(!output.status.success(), "the helper must stop");
    let message = stderr(&output);
    let line = format!("display_dir = \"{}\"", helper.display_dir().display());
    assert!(message.contains(&line), "{message}");
    assert!(
        message.contains(&helper.config_file().display().to_string()),
        "{message}"
    );
    assert_eq!(snapshot(&helper.unit_dir())?, units_before);
    assert_eq!(snapshot_tree(&helper.state_dir())?, state_before);
    assert!(helper.systemctl_calls().is_empty());
    Ok(())
}

#[test]
fn an_unexpected_display_dir_stops_the_helper() -> Result<()> {
    let helper = Helper::new()?;
    let other = helper.path("runtime").join("elsewhere/display");
    helper.write_config_with_display("reserved-event", Some(&other))?;
    helper.write_old_units()?;
    let units_before = snapshot(&helper.unit_dir())?;
    let state_before = snapshot_tree(&helper.state_dir())?;

    for args in [&["--units-only"][..], &["--units-only", "--display"][..]] {
        let output = helper.run(args)?;

        assert!(!output.status.success(), "the helper must stop: {args:?}");
        let message = stderr(&output);
        assert!(message.contains(&other.display().to_string()), "{message}");
        assert!(
            message.contains(&helper.display_dir().display().to_string()),
            "{message}"
        );
        assert_eq!(snapshot(&helper.unit_dir())?, units_before);
        assert_eq!(snapshot_tree(&helper.state_dir())?, state_before);
    }
    Ok(())
}

#[test]
fn a_display_dir_that_is_the_drop_directory_stops_the_helper() -> Result<()> {
    let helper = Helper::new()?;
    helper.write_config_with_display("reserved-event", Some(&helper.watch_dir()))?;
    helper.write_old_units()?;
    let units_before = snapshot(&helper.unit_dir())?;

    let output = helper.run(&["--units-only"])?;

    assert!(!output.status.success(), "the helper must stop");
    let message = stderr(&output);
    assert!(message.contains("drop directory"), "{message}");
    assert!(message.contains("ADR 0008"), "{message}");
    assert_eq!(snapshot(&helper.unit_dir())?, units_before);
    Ok(())
}

#[test]
fn units_only_does_not_write_an_unchanged_unit_again() -> Result<()> {
    use std::os::unix::fs::MetadataExt;

    let helper = Helper::new()?;
    helper.write_config_with_display("reserved-event", Some(&helper.display_dir()))?;
    let first = helper.run(&["--units-only"])?;
    assert!(first.status.success(), "{}", stderr(&first));
    let units_before = snapshot(&helper.unit_dir())?;
    let inodes_before = [
        fs::metadata(helper.publisher_unit())?.ino(),
        fs::metadata(helper.producer_unit())?.ino(),
    ];

    let second = helper.run(&["--units-only"])?;

    assert!(second.status.success(), "{}", stderr(&second));
    assert_eq!(
        snapshot(&helper.unit_dir())?,
        units_before,
        "no write, no backup"
    );
    let inodes_after = [
        fs::metadata(helper.publisher_unit())?.ino(),
        fs::metadata(helper.producer_unit())?.ino(),
    ];
    assert_eq!(inodes_after, inodes_before, "no rename over the unit");
    let stdout = String::from_utf8_lossy(&second.stdout);
    for unit in [helper.publisher_unit(), helper.producer_unit()] {
        assert!(
            stdout.contains(&format!("Unit not changed: {}", unit.display())),
            "{stdout}"
        );
    }
    Ok(())
}

#[test]
fn units_only_with_start_reloads_then_restarts_both_units() -> Result<()> {
    let helper = Helper::new()?;
    helper.write_config("reserved-event")?;
    helper.write_old_units()?;

    let output = helper.run_started(&["--units-only"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let calls = helper.systemctl_calls();
    let reload = calls
        .iter()
        .position(|call| call == "--user daemon-reload")
        .with_context(|| format!("no daemon-reload: {calls:?}"))?;
    let restart_call = format!("--user restart {PUBLISHER_UNIT_NAME} {PRODUCER_UNIT_NAME}");
    let restart = calls
        .iter()
        .position(|call| *call == restart_call)
        .with_context(|| format!("no restart of both units: {calls:?}"))?;
    assert!(reload < restart, "{calls:?}");
    assert!(
        !calls
            .iter()
            .any(|call| call.contains("enable") || call.contains(" start ")),
        "{calls:?}"
    );
    Ok(())
}

#[test]
fn units_only_reads_the_display_dir_of_its_own_target_only() -> Result<()> {
    let helper = Helper::new()?;
    let mut text = helper.write_config("reserved-event")?;
    text.push_str(&format!(
        "\n[[target]]\nname = \"other\"\nevent_id = \"other-event\"\ntoken_file = \"{}\"\ndisplay_dir = \"{}\"\n",
        helper.path("home").join("other.token").display(),
        helper.display_dir().display()
    ));
    fs::write(helper.config_file(), &text)?;

    let output = helper.run(&["--units-only"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let producer = fs::read_to_string(helper.producer_unit())?;
    assert!(!producer.contains("display"), "{producer}");
    Ok(())
}
