//! `setup-mixxx-musicindex` keeps an existing event (reserved safety task 003).
//!
//! Each test runs the helper with stub programs, a temporary configuration
//! home, a temporary runtime directory, a stub card directory and
//! `--no-start`. A stub `systemctl` on `PATH` records each call, so a test
//! can never reach the real user manager.

use std::collections::BTreeMap;
use std::fs;
use std::os::unix::fs::{PermissionsExt, symlink};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use anyhow::{Context, Result};
use tempfile::TempDir;

const MARKER: &str = "# Generated by setup-mixxx-musicindex.sh";
const PLACEHOLDER: &str = "replace-with-provisioned-event-guid";

/// One isolated run environment for the setup helper.
struct Helper {
    root: TempDir,
}

impl Helper {
    fn new() -> Result<Self> {
        let root = tempfile::tempdir()?;
        let helper = Self { root };
        for dir in ["config", "runtime", "home", "asound", "bin"] {
            fs::create_dir_all(helper.path(dir))?;
        }
        symlink("card31", helper.path("asound").join("V4V"))?;
        let publisher_log = helper.publisher_log();
        let systemctl_log = helper.systemctl_log();
        helper.write_stub(
            "musicindex-live-publisher",
            &format!(
                r#"#!/bin/sh
printf '%s\n' "$*" >> '{log}'
if [ "$1" = provision ]; then
  token_file=
  while [ $# -gt 0 ]; do
    case "$1" in
      --token-file) token_file=$2; shift 2 ;;
      *) shift ;;
    esac
  done
  printf 'stub-token\n' > "$token_file"
  echo 'Live item provisioned.'
  echo 'The broadcaster token was returned exactly once and cannot be recovered by the relay.'
  echo "Token written to $token_file"
  echo
  echo '[[target]]'
  echo 'name = "default"'
  echo 'event_id = "stub-event"'
  echo "token_file = \"$token_file\""
fi
"#,
                log = publisher_log.display()
            ),
        )?;
        helper.write_stub("mixxx-now-playing", "#!/bin/sh\nexit 0\n")?;
        helper.write_stub(
            "systemctl",
            &format!(
                "#!/bin/sh\nprintf '%s\\n' \"$*\" >> '{}'\nexit 0\n",
                systemctl_log.display()
            ),
        )?;
        Ok(helper)
    }

    fn path(&self, name: &str) -> PathBuf {
        self.root.path().join(name)
    }

    fn write_stub(&self, name: &str, body: &str) -> Result<()> {
        let path = self.path("bin").join(name);
        fs::write(&path, body)?;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
        Ok(())
    }

    fn publisher_log(&self) -> PathBuf {
        self.path("publisher.log")
    }

    fn systemctl_log(&self) -> PathBuf {
        self.path("systemctl.log")
    }

    fn state_dir(&self) -> PathBuf {
        self.path("config").join("musicindex-live-publisher/mixxx")
    }

    fn config_file(&self) -> PathBuf {
        self.state_dir().join("config.toml")
    }

    fn token_dir(&self) -> PathBuf {
        self.state_dir().join("tokens")
    }

    fn unit_dir(&self) -> PathBuf {
        self.path("config").join("systemd/user")
    }

    fn publisher_unit(&self) -> PathBuf {
        self.unit_dir()
            .join("musicindex-live-publisher@mixxx.service")
    }

    fn producer_unit(&self) -> PathBuf {
        self.unit_dir().join("mixxx-now-playing.service")
    }

    fn write_config(&self, event_id: &str) -> Result<String> {
        fs::create_dir_all(self.token_dir())?;
        let text = format!(
            "{MARKER}\n\
             watch_dir = \"/run/user/0/musicindex-live-publisher/mixxx/nowplaying\"\n\
             endpoint = \"https://relay.invalid\"\n\
             \n\
             [[target]]\n\
             name = \"default\"\n\
             event_id = \"{event_id}\"\n\
             token_file = \"{}\"\n",
            self.path("home").join("reserved.token").display()
        );
        fs::write(self.config_file(), &text)?;
        Ok(text)
    }

    fn write_old_units(&self) -> Result<()> {
        fs::create_dir_all(self.unit_dir())?;
        fs::write(
            self.publisher_unit(),
            format!("{MARKER}\n[Service]\nExecStart=/old/publisher\n"),
        )?;
        fs::write(
            self.producer_unit(),
            format!("{MARKER}\n[Service]\nPrivateDevices=true\n"),
        )?;
        Ok(())
    }

    fn run(&self, args: &[&str]) -> Result<Output> {
        let script =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("scripts/setup-mixxx-musicindex.sh");
        let bin = self.path("bin");
        let output = Command::new("/bin/bash")
            .arg(script)
            .arg("--no-start")
            .args(args)
            .env_clear()
            .env("PATH", format!("{}:/usr/bin:/bin", bin.display()))
            .env("HOME", self.path("home"))
            .env("XDG_CONFIG_HOME", self.path("config"))
            .env("XDG_RUNTIME_DIR", self.path("runtime"))
            .env("MUSICINDEX_ASOUND_DIR", self.path("asound"))
            .env("MUSICINDEX_ENDPOINT", "http://127.0.0.1:9")
            .env(
                "MUSICINDEX_LIVE_PUBLISHER_BIN",
                bin.join("musicindex-live-publisher"),
            )
            .env("MIXXX_NOW_PLAYING_BIN", bin.join("mixxx-now-playing"))
            .output()
            .context("run the setup helper")?;
        Ok(output)
    }

    fn publisher_calls(&self) -> Vec<String> {
        read_lines(&self.publisher_log())
    }

    fn systemctl_calls(&self) -> Vec<String> {
        read_lines(&self.systemctl_log())
    }

    fn config_backups(&self) -> Result<Vec<PathBuf>> {
        let mut backups = Vec::new();
        for entry in fs::read_dir(self.state_dir())? {
            let path = entry?.path();
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            if name.starts_with("config.toml.bak.") {
                backups.push(path);
            }
        }
        Ok(backups)
    }
}

fn read_lines(path: &Path) -> Vec<String> {
    fs::read_to_string(path)
        .map(|text| text.lines().map(str::to_owned).collect())
        .unwrap_or_default()
}

/// The name, the link target or the content of each entry in a directory.
fn snapshot(dir: &Path) -> Result<BTreeMap<String, String>> {
    let mut entries = BTreeMap::new();
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        let name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        let value = match fs::read_link(&path) {
            Ok(target) => format!("link:{}", target.display()),
            Err(_) => fs::read_to_string(&path)?,
        };
        entries.insert(name, value);
    }
    Ok(entries)
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

#[test]
fn a_real_event_stops_the_helper_without_force() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;

    let output = helper.run(&[])?;

    assert!(!output.status.success(), "the helper must stop");
    let message = stderr(&output);
    assert!(message.contains("reserved-event"), "{message}");
    assert!(message.contains("No relay request ran"), "{message}");
    assert!(message.contains("--units-only"), "{message}");
    assert_eq!(fs::read_to_string(helper.config_file())?, before);
    assert!(helper.config_backups()?.is_empty());
    assert!(helper.publisher_calls().is_empty());
    assert!(!helper.publisher_unit().exists());
    assert!(!helper.producer_unit().exists());
    Ok(())
}

#[test]
fn force_backs_up_a_real_event_config_and_provisions() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;

    let output = helper.run(&["--force"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let backups = helper.config_backups()?;
    assert_eq!(backups.len(), 1, "one config backup");
    assert_eq!(fs::read_to_string(&backups[0])?, before);
    let calls = helper.publisher_calls();
    assert_eq!(calls.len(), 1, "{calls:?}");
    assert!(calls[0].starts_with("provision "), "{calls:?}");
    let config = fs::read_to_string(helper.config_file())?;
    assert!(config.contains("event_id = \"stub-event\""), "{config}");
    Ok(())
}

#[test]
fn a_placeholder_config_provisions_without_force() -> Result<()> {
    let helper = Helper::new()?;
    helper.write_config(PLACEHOLDER)?;

    let output = helper.run(&[])?;

    assert!(output.status.success(), "{}", stderr(&output));
    let calls = helper.publisher_calls();
    assert_eq!(calls.len(), 1, "{calls:?}");
    assert!(calls[0].starts_with("provision "), "{calls:?}");
    let config = fs::read_to_string(helper.config_file())?;
    assert!(config.contains("event_id = \"stub-event\""), "{config}");
    assert!(!config.contains(PLACEHOLDER), "{config}");
    Ok(())
}

#[test]
fn a_fresh_run_provisions_and_no_start_runs_no_systemctl() -> Result<()> {
    let helper = Helper::new()?;

    let output = helper.run(&[])?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(helper.publisher_calls().len(), 1);
    assert!(helper.token_dir().join("default.token").exists());
    assert!(helper.publisher_unit().exists());
    assert!(helper.producer_unit().exists());
    assert!(
        helper.systemctl_calls().is_empty(),
        "{:?}",
        helper.systemctl_calls()
    );
    Ok(())
}

#[test]
fn a_token_link_that_points_nowhere_stops_the_helper() -> Result<()> {
    let helper = Helper::new()?;
    fs::create_dir_all(helper.token_dir())?;
    let token = helper.token_dir().join("default.token");
    symlink(helper.path("home").join("missing.token"), &token)?;

    let output = helper.run(&[])?;

    assert!(!output.status.success(), "the helper must stop");
    assert!(
        stderr(&output).contains("existing token"),
        "{}",
        stderr(&output)
    );
    assert!(helper.publisher_calls().is_empty());
    assert!(fs::symlink_metadata(&token)?.file_type().is_symlink());
    assert!(!helper.config_file().exists());
    Ok(())
}

#[test]
fn units_only_writes_the_units_and_nothing_else() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;
    fs::write(helper.token_dir().join("default.token"), "kept-token\n")?;
    fs::write(helper.token_dir().join("other.token"), "other-token\n")?;
    symlink("/nowhere", helper.token_dir().join("linked.token"))?;
    let tokens_before = snapshot(&helper.token_dir())?;
    helper.write_old_units()?;

    let output = helper.run(&["--units-only"])?;

    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(fs::read_to_string(helper.config_file())?, before);
    assert!(helper.config_backups()?.is_empty());
    assert_eq!(snapshot(&helper.token_dir())?, tokens_before);
    assert!(
        helper.publisher_calls().is_empty(),
        "{:?}",
        helper.publisher_calls()
    );
    assert!(
        helper.systemctl_calls().is_empty(),
        "{:?}",
        helper.systemctl_calls()
    );

    let producer = fs::read_to_string(helper.producer_unit())?;
    assert!(producer.contains("PrivateDevices=false"), "{producer}");
    let publisher = fs::read_to_string(helper.publisher_unit())?;
    assert!(
        publisher.contains(&format!("--config {}", helper.config_file().display())),
        "{publisher}"
    );
    let unit_names: Vec<String> = snapshot(&helper.unit_dir())?.into_keys().collect();
    for unit in [
        "musicindex-live-publisher@mixxx.service",
        "mixxx-now-playing.service",
    ] {
        assert!(
            unit_names
                .iter()
                .any(|name| name.starts_with(&format!("{unit}.bak."))),
            "no backup of {unit}: {unit_names:?}"
        );
    }
    Ok(())
}

#[test]
fn units_only_without_a_config_stops() -> Result<()> {
    let helper = Helper::new()?;

    let output = helper.run(&["--units-only"])?;

    assert!(!output.status.success(), "the helper must stop");
    assert!(stderr(&output).contains("--units-only needs an existing config"));
    assert!(helper.publisher_calls().is_empty());
    assert!(helper.systemctl_calls().is_empty());
    assert!(!helper.publisher_unit().exists());
    assert!(!helper.producer_unit().exists());
    assert!(!helper.state_dir().exists());
    Ok(())
}

#[test]
fn units_only_checks_the_card() -> Result<()> {
    let helper = Helper::new()?;
    let before = helper.write_config("reserved-event")?;
    fs::remove_file(helper.path("asound").join("V4V"))?;

    let output = helper.run(&["--units-only"])?;

    assert!(!output.status.success(), "the helper must stop");
    assert!(
        stderr(&output).contains("MIDI card is missing"),
        "{}",
        stderr(&output)
    );
    assert_eq!(fs::read_to_string(helper.config_file())?, before);
    assert!(!helper.publisher_unit().exists());
    Ok(())
}
