#!/usr/bin/env bash
set -euo pipefail

program=${0##*/}
generated_marker="# Generated by setup-mixxx-musicindex.sh"

endpoint=${MUSICINDEX_ENDPOINT:-https://api.musicindex.org}
mode=permanent
start_services=1
force=0

fallback_title=${MUSICINDEX_FALLBACK_TITLE:-Mixxx Live}
fallback_name=${MUSICINDEX_FALLBACK_NAME:-Station}
fallback_type=${MUSICINDEX_FALLBACK_TYPE:-node}
fallback_address=${MUSICINDEX_FALLBACK_ADDRESS:-}
fallback_split=${MUSICINDEX_FALLBACK_SPLIT:-100}
fallback_image=${MUSICINDEX_FALLBACK_IMAGE:-}
fallback_value_block=${MUSICINDEX_FALLBACK_VALUE_BLOCK:-}
value_type=${MUSICINDEX_VALUE_TYPE:-lightning}
value_method=${MUSICINDEX_VALUE_METHOD:-keysend}
value_suggested=${MUSICINDEX_VALUE_SUGGESTED:-}

publisher_bin=${MUSICINDEX_LIVE_PUBLISHER_BIN:-/usr/bin/musicindex-live-publisher}
producer_bin=${MIXXX_NOW_PLAYING_BIN:-/usr/bin/mixxx-now-playing}

instance=mixxx
target=default

usage() {
  cat <<'USAGE'
Usage:
  setup-mixxx-musicindex [--permanent|--temporary] [--fallback-value-block FILE | --fallback-address ADDRESS] [options]

Provisions a MusicIndex live item for Mixxx, writes the broadcaster token and
publisher config, generates user systemd units, and starts the Mixxx pipeline.

Modes:
  --permanent          Store config/token under ~/.config and enable services.
  --temporary          Store config/token under XDG_RUNTIME_DIR and start
                       services only for this login session.

Options:
  --endpoint URL       MusicIndex relay endpoint.
                       Default: https://api.musicindex.org
  --fallback-address ADDRESS
                       Shortcut for one Podcasting valueRecipient address.
                       If neither fallback option is set, the publisher uses a
                       default dead fallback route and logs a warning.
                       Or set MUSICINDEX_FALLBACK_ADDRESS.
  --fallback-value-block FILE
                       TOML fallback value block fragment. Or set
                       MUSICINDEX_FALLBACK_VALUE_BLOCK.
  --value-type TEXT    Value model type for the shortcut. Default: lightning
                       Or set MUSICINDEX_VALUE_TYPE.
  --value-method TEXT  Value model method for the shortcut. Default: keysend
                       Or set MUSICINDEX_VALUE_METHOD.
  --value-suggested TEXT
                       Optional value model suggested amount for the shortcut.
                       Or set MUSICINDEX_VALUE_SUGGESTED.
  --fallback-title TEXT
                       Fallback title. Default: Mixxx Live
  --fallback-name TEXT
                       Fallback destination name. Default: Station
  --fallback-type TEXT
                       Fallback destination type for the shortcut.
                       Default: node
  --fallback-split DECIMAL
                       Fallback split as a string value. Default: 100
  --fallback-image URL Optional fallback image URL.
  --force              Replace existing generated files and back up conflicts.
  --no-start           Write files but do not start services.
  -h, --help           Show this help.

Examples:
  setup-mixxx-musicindex
  setup-mixxx-musicindex --fallback-value-block ~/.config/musicindex-live-publisher/mixxx-fallback.toml
  setup-mixxx-musicindex --fallback-address "$MUSICINDEX_FALLBACK_ADDRESS"
  setup-mixxx-musicindex --fallback-type lnaddress --value-method lnaddress --fallback-address station@example.com
USAGE
}

die() {
  printf '%s: %s\n' "$program" "$*" >&2
  exit 1
}

warn() {
  printf '%s: warning: %s\n' "$program" "$*" >&2
}

require_arg() {
  local flag=$1
  local value=${2-}
  [[ -n "$value" ]] || die "$flag requires a value"
  printf '%s' "$value"
}

while (($#)); do
  case "$1" in
    --permanent)
      mode=permanent
      shift
      ;;
    --temporary)
      mode=temporary
      shift
      ;;
    --endpoint)
      endpoint=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --fallback-address)
      fallback_address=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --fallback-value-block|--value-block)
      fallback_value_block=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --value-type)
      value_type=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --value-method)
      value_method=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --value-suggested)
      value_suggested=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --fallback-title|--station-title)
      fallback_title=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --fallback-name)
      fallback_name=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --fallback-type)
      fallback_type=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --fallback-split)
      fallback_split=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --fallback-image)
      fallback_image=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    --no-start)
      start_services=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

if [[ -z "$fallback_value_block" ]]; then
  if [[ -n "$fallback_address" ]]; then
    [[ -n "$value_type" ]] || die "--value-type must not be empty"
    [[ -n "$value_method" ]] || die "--value-method must not be empty"
    [[ -n "$fallback_type" ]] || die "--fallback-type must not be empty"
    [[ "$fallback_split" =~ ^[0-9]+([.][0-9]+)?$ ]] \
      || die "--fallback-split must be a decimal string such as 100 or 49.51"
    case "$fallback_address" in
      YOUR_*|*your-*|*replace-with*|03...)
        die "--fallback-address is still an example placeholder"
        ;;
    esac
  else
    warn "no fallback payment route configured; generated config will use the publisher's default dead fallback route while idle/non-V4V"
    warn "configure --fallback-value-block or --fallback-address later if this stream should receive station fallback payments"
  fi
fi

reject_newline() {
  local name=$1
  local value=$2
  case "$value" in
    *$'\n'*|*$'\r'*)
      die "$name must not contain newlines"
      ;;
  esac
}

for name in endpoint fallback_title fallback_name fallback_type fallback_address fallback_split fallback_image fallback_value_block value_type value_method value_suggested; do
  reject_newline "$name" "${!name}"
done

if [[ -n "$fallback_value_block" ]]; then
  [[ -r "$fallback_value_block" ]] || die "cannot read fallback value block: $fallback_value_block"
  [[ -s "$fallback_value_block" ]] || die "fallback value block is empty: $fallback_value_block"
  if grep -Eq '^[[:space:]]*(watch_dir|endpoint|event_id|token_file)[[:space:]]*=' "$fallback_value_block"; then
    die "fallback value block must not contain publisher config fields"
  fi
  if grep -Eq '^[[:space:]]*\[\[?target' "$fallback_value_block"; then
    die "fallback value block must be a fallback fragment, not a full target config"
  fi
  if grep -Eq 'YOUR_|your-|replace-with|03\.\.\.' "$fallback_value_block"; then
    die "fallback value block still contains an example placeholder"
  fi
  grep -Eq '^[[:space:]]*title[[:space:]]*=' "$fallback_value_block" \
    || die "fallback value block must define title"
  grep -Eq '^[[:space:]]*(model[[:space:]]*=|\[(value\.)?model\])' "$fallback_value_block" \
    || die "fallback value block must define model"
  grep -Eq '^[[:space:]]*(destinations[[:space:]]*=|\[\[?(value\.)?destinations\]\]?)' "$fallback_value_block" \
    || die "fallback value block must define destinations"
fi

resolve_command() {
  local command_name=$1
  local resolved
  resolved=$(command -v "$command_name" 2>/dev/null) \
    || die "$command_name is not executable; install musicindex-live-publisher first"
  printf '%s' "$resolved"
}

publisher_bin=$(resolve_command "$publisher_bin")
producer_bin=$(resolve_command "$producer_bin")

if [[ "$start_services" -eq 1 ]]; then
  command -v systemctl >/dev/null 2>&1 || die "systemctl is required to start user services"
  systemctl --user show-environment >/dev/null 2>&1 \
    || die "systemd user manager is not available; rerun with --no-start or start a user session"
fi

uid=$(id -u)
runtime_root=${XDG_RUNTIME_DIR:-/run/user/$uid}
config_home=${XDG_CONFIG_HOME:-$HOME/.config}
watch_dir=$runtime_root/musicindex-live-publisher/$instance/nowplaying
txt_file=$watch_dir/now-playing.txt
unit_dir=$config_home/systemd/user

case "$mode" in
  permanent)
    state_dir=$config_home/musicindex-live-publisher/$instance
    ;;
  temporary)
    state_dir=$runtime_root/musicindex-live-publisher-setup/$instance
    ;;
  *)
    die "unsupported mode: $mode"
    ;;
esac

config_file=$state_dir/config.toml
token_dir=$state_dir/tokens
token_file=$token_dir/$target.token
publisher_unit=$unit_dir/musicindex-live-publisher@$instance.service
producer_unit=$unit_dir/mixxx-now-playing.service
publisher_unit_name=musicindex-live-publisher@$instance.service
producer_unit_name=mixxx-now-playing.service
stamp=$(date -u '+%Y%m%dT%H%M%SZ')

reject_systemd_arg() {
  local name=$1
  local value=$2
  case "$value" in
    *[[:space:]]*|*%*)
      die "$name contains whitespace or %, which this simple generated unit does not escape: $value"
      ;;
  esac
}

for name in publisher_bin producer_bin config_file watch_dir txt_file; do
  reject_systemd_arg "$name" "${!name}"
done

toml_string() {
  local value=$1
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '"%s"' "$value"
}

emit_fallback_value_block() {
  if [[ -n "$fallback_value_block" ]]; then
    sed -E \
      -e 's/^[[:space:]]*\[model\][[:space:]]*$/    [target.fallback.value.model]/' \
      -e 's/^[[:space:]]*\[value\][[:space:]]*$/    [target.fallback.value]/' \
      -e 's/^[[:space:]]*\[value\.model\][[:space:]]*$/    [target.fallback.value.model]/' \
      -e 's/^[[:space:]]*\[\[destinations\]\][[:space:]]*$/    [[target.fallback.value.destinations]]/' \
      -e 's/^[[:space:]]*\[\[value\.destinations\]\][[:space:]]*$/    [[target.fallback.value.destinations]]/' \
      -e 's/^/  /' \
      "$fallback_value_block"
    return
  fi

  printf '  title = %s\n' "$(toml_string "$fallback_title")"
  if [[ -n "$fallback_image" ]]; then
    printf '  image = %s\n' "$(toml_string "$fallback_image")"
  fi
  printf '\n'
  printf '    [target.fallback.value.model]\n'
  printf '    type = %s\n' "$(toml_string "$value_type")"
  printf '    method = %s\n' "$(toml_string "$value_method")"
  if [[ -n "$value_suggested" ]]; then
    printf '    suggested = %s\n' "$(toml_string "$value_suggested")"
  fi
  printf '\n'
  printf '    [[target.fallback.value.destinations]]\n'
  printf '    name = %s\n' "$(toml_string "$fallback_name")"
  printf '    type = %s\n' "$(toml_string "$fallback_type")"
  printf '    address = %s\n' "$(toml_string "$fallback_address")"
  printf '    split = %s\n' "$(toml_string "$fallback_split")"
}

file_has_marker() {
  local path=$1
  [[ -e "$path" ]] && grep -Fq "$generated_marker" "$path"
}

can_replace_config() {
  local path=$1
  [[ ! -e "$path" ]] && return 0
  file_has_marker "$path" && return 0
  grep -Fq "replace-with-provisioned-event-guid" "$path" && return 0
  [[ "$force" -eq 1 ]]
}

can_replace_generated_file() {
  local path=$1
  [[ ! -e "$path" ]] && return 0
  file_has_marker "$path" && return 0
  [[ "$force" -eq 1 ]]
}

backup_file() {
  local path=$1
  [[ -e "$path" ]] || return 0
  local backup=$path.bak.$stamp
  cp -p "$path" "$backup"
  warn "backed up $path to $backup"
}

write_generated_file() {
  local path=$1
  local file_mode=$2
  local tmp
  tmp=$(mktemp "$path.tmp.XXXXXX")
  cat > "$tmp"
  chmod "$file_mode" "$tmp"
  mv "$tmp" "$path"
}

install -d -m 0700 "$state_dir" "$token_dir"
install -d -m 0755 "$unit_dir"

can_replace_config "$config_file" \
  || die "refusing to replace existing config $config_file; rerun with --force or edit it manually"
can_replace_generated_file "$publisher_unit" \
  || die "refusing to replace existing unit $publisher_unit; rerun with --force or edit it manually"
can_replace_generated_file "$producer_unit" \
  || die "refusing to replace existing unit $producer_unit; rerun with --force or edit it manually"

if [[ -e "$token_file" ]]; then
  [[ "$force" -eq 1 ]] \
    || die "refusing to replace existing token $token_file; rerun with --force to provision a new live item"
  mv "$token_file" "$token_file.bak.$stamp"
  warn "backed up $token_file to $token_file.bak.$stamp"
fi

printf 'Provisioning MusicIndex live item at %s...\n' "$endpoint"
provision_output=$("$publisher_bin" provision \
  --endpoint "$endpoint" \
  --target "$target" \
  --token-file "$token_file")
printf '%s\n' "$provision_output"
event_id=$(printf '%s\n' "$provision_output" | sed -n 's/^event_id = "\(.*\)"$/\1/p' | tail -n 1)
[[ -n "$event_id" ]] || die "could not parse event_id from provision output"

backup_file "$config_file"
{
  printf '%s\n' "$generated_marker"
  printf '# Mode: %s\n' "$mode"
  printf '# The %s unit overrides watch_dir with --watch-dir.\n' "$publisher_unit_name"
  printf 'watch_dir = %s\n' "$(toml_string "$watch_dir")"
  printf 'endpoint = %s\n' "$(toml_string "$endpoint")"
  printf '\n'
  printf '[[target]]\n'
  printf 'name = %s\n' "$(toml_string "$target")"
  printf 'event_id = %s\n' "$(toml_string "$event_id")"
  printf 'token_file = %s\n' "$(toml_string "$token_file")"
  if [[ -n "$fallback_value_block" || -n "$fallback_address" ]]; then
    printf '\n'
    printf '  [target.fallback]\n'
    emit_fallback_value_block
  else
    printf '\n'
    printf '# No fallback payment route configured.\n'
    printf '# The publisher logs a warning and uses a dead fallback route while idle/non-V4V.\n'
  fi
} | write_generated_file "$config_file" 0600

backup_file "$publisher_unit"
write_generated_file "$publisher_unit" 0644 <<EOF
$generated_marker
[Unit]
Description=MusicIndex live publisher for Mixxx
Documentation=file:///usr/share/doc/musicindex-live-publisher/musicindex-live-publisher-deploy.md
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
ExecStart=$publisher_bin --config $config_file --watch-dir $watch_dir
Restart=on-failure
RestartSec=5s

RuntimeDirectory=musicindex-live-publisher/$instance/nowplaying
RuntimeDirectoryMode=0700
RuntimeDirectoryPreserve=yes

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictSUIDSGID=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
UMask=0077

[Install]
WantedBy=default.target
EOF

backup_file "$producer_unit"
write_generated_file "$producer_unit" 0644 <<EOF
$generated_marker
[Unit]
Description=Mixxx now-playing producer for MusicIndex
Documentation=file:///usr/share/doc/musicindex-live-publisher/musicindex-live-publisher-deploy.md
Wants=$publisher_unit_name
After=$publisher_unit_name

[Service]
Type=simple
ExecStart=$producer_bin --format json --target $target --id3-file $watch_dir/$target.json --txt-file $txt_file
Restart=always
RestartSec=10s

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
RuntimeDirectory=musicindex-live-publisher/$instance/nowplaying
RuntimeDirectoryMode=0700
RuntimeDirectoryPreserve=yes
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictSUIDSGID=true
LockPersonality=true

[Install]
WantedBy=default.target
EOF

printf 'Wrote config: %s\n' "$config_file"
printf 'Wrote token: %s\n' "$token_file"
printf 'Wrote unit: %s\n' "$publisher_unit"
printf 'Wrote unit: %s\n' "$producer_unit"
printf 'Event ID: %s\n' "$event_id"

mixxx_running=unknown
if command -v pgrep >/dev/null 2>&1; then
  if pgrep -x mixxx >/dev/null 2>&1 || pgrep -f '(^|/)mixxx([[:space:]]|$)' >/dev/null 2>&1; then
    mixxx_running=yes
  else
    mixxx_running=no
  fi
fi

if [[ "$start_services" -eq 1 ]]; then
  systemctl --user daemon-reload
  systemctl --user reset-failed "$publisher_unit_name" "$producer_unit_name" >/dev/null 2>&1 || true

  if [[ "$mode" == permanent ]]; then
    systemctl --user enable --now "$publisher_unit_name" "$producer_unit_name"
  else
    systemctl --user start "$publisher_unit_name" "$producer_unit_name"
  fi

  sleep 1
  if ! systemctl --user is-active --quiet "$publisher_unit_name"; then
    systemctl --user --no-pager --full status "$publisher_unit_name" >&2 || true
    die "$publisher_unit_name did not become active"
  fi

  if [[ "$mixxx_running" == yes ]]; then
    sleep 1
    if ! systemctl --user is-active --quiet "$producer_unit_name"; then
      systemctl --user --no-pager --full status "$producer_unit_name" >&2 || true
      die "$producer_unit_name did not stay active while Mixxx is running"
    fi
  elif [[ "$mixxx_running" == no ]]; then
    warn "Mixxx is not running; $producer_unit_name will restart until Mixxx starts"
  else
    warn "could not check whether Mixxx is running because pgrep is unavailable"
  fi

  printf 'Started: %s\n' "$publisher_unit_name"
  printf 'Started: %s\n' "$producer_unit_name"
else
  printf 'Start with:\n'
  if [[ "$mode" == permanent ]]; then
    printf '  systemctl --user enable --now %s %s\n' "$publisher_unit_name" "$producer_unit_name"
  else
    printf '  systemctl --user start %s %s\n' "$publisher_unit_name" "$producer_unit_name"
  fi
fi

if [[ "$mode" == temporary ]]; then
  warn "temporary mode uses runtime files under $runtime_root; rerun after logout or reboot"
  warn "generated user units remain in $unit_dir but are not enabled"
fi

printf 'Producer drop file: %s/%s.json\n' "$watch_dir" "$target"
printf 'Text metadata file: %s\n' "$txt_file"
