#!/usr/bin/env bash
set -euo pipefail

program=${0##*/}
generated_marker="# Generated by setup-mixxx-musicindex.sh"

endpoint=${MUSICINDEX_ENDPOINT:-https://api.musicindex.org}
mode=permanent
start_services=1
force=0
units_only=0
placeholder_event_id=replace-with-provisioned-event-guid

publisher_bin=${MUSICINDEX_LIVE_PUBLISHER_BIN:-/usr/bin/musicindex-live-publisher}
producer_bin=${MIXXX_NOW_PLAYING_BIN:-/usr/bin/mixxx-now-playing}

instance=mixxx
target=default

usage() {
  cat <<'USAGE'
Usage:
  setup-mixxx-musicindex [--permanent|--temporary] [options]

Provisions a MusicIndex live item for Mixxx, writes the broadcaster token and
publisher config, generates user systemd units, and starts the Mixxx pipeline.

The publisher uses a fixed dead block while idle or playing non-V4V audio
(ADR 0005). No option in this script changes it.

The script checks the V4V MIDI card before it writes a file (ADR 0006). If
the card is missing, the script stops. MUSICINDEX_ASOUND_DIR replaces
/proc/asound for this check.

Modes:
  --permanent          Store config/token under ~/.config and enable services.
  --temporary          Store config/token under XDG_RUNTIME_DIR and start
                       services only for this login session.

Options:
  --endpoint URL       MusicIndex relay endpoint.
                       Default: https://api.musicindex.org
  --force              Replace existing generated files and back up conflicts.
                       Only this option replaces a config with a real event
                       ID. The script then provisions a new live item.
  --units-only         Write the two user units again. Use this to upgrade.
                       The config must exist. The script reads no token,
                       changes no config or token, and sends no relay request.
  --no-start           Write files but do not run systemctl.
  -h, --help           Show this help.

A config that names a real event stops the script before the relay request,
unless you give --force.

Examples:
  setup-mixxx-musicindex
  setup-mixxx-musicindex --temporary
  setup-mixxx-musicindex --units-only
USAGE
}

die() {
  printf '%s: %s\n' "$program" "$*" >&2
  exit 1
}

warn() {
  printf '%s: warning: %s\n' "$program" "$*" >&2
}

require_arg() {
  local flag=$1
  local value=${2-}
  [[ -n "$value" ]] || die "$flag requires a value"
  printf '%s' "$value"
}

while (($#)); do
  case "$1" in
    --permanent)
      mode=permanent
      shift
      ;;
    --temporary)
      mode=temporary
      shift
      ;;
    --endpoint)
      endpoint=$(require_arg "$1" "${2-}")
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    --units-only)
      units_only=1
      shift
      ;;
    --no-start)
      start_services=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

reject_newline() {
  local name=$1
  local value=$2
  case "$value" in
    *$'\n'*|*$'\r'*)
      die "$name must not contain newlines"
      ;;
  esac
}

reject_newline endpoint "$endpoint"

# ADR 0006 §Card Setup: the producer reads the V4V MIDI card. Check the card
# before this script writes a file. MUSICINDEX_ASOUND_DIR replaces /proc/asound
# for a test without a real card.
asound_dir=${MUSICINDEX_ASOUND_DIR:-/proc/asound}
connector_card=V4V
connector_card_number=31
configuration_runbook=/usr/share/doc/musicindex-live-publisher/musicindex-live-publisher-configuration.md

check_connector_card() {
  local link=$asound_dir/$connector_card
  local card
  local number

  if [[ ! -e "$link" && ! -L "$link" ]]; then
    printf '%s: the %s MIDI card is missing: %s does not exist.\n' \
      "$program" "$connector_card" "$link" >&2
    printf '%s: Reboot after the package install. The card exists only after a reboot.\n' \
      "$program" >&2
    printf '%s: If this computer already uses snd-virmidi, merge the options first.\n' \
      "$program" >&2
    printf '%s: See section "MIDI Connector" in %s.\n' \
      "$program" "$configuration_runbook" >&2
    exit 1
  fi

  card=$(readlink "$link") \
    || die "$link is not a link to a card. See section \"MIDI Connector\" in $configuration_runbook."
  card=${card##*/}
  number=${card#card}
  [[ "$card" == card* && "$number" =~ ^[0-9]+$ ]] \
    || die "$link points to $card, not to a card. See section \"MIDI Connector\" in $configuration_runbook."

  if [[ "$number" == "$connector_card_number" ]]; then
    printf 'MIDI connector card: %s is card %s. Mixxx port: VirMIDI %s-0\n' \
      "$connector_card" "$number" "$number"
  else
    warn "the $connector_card MIDI card is card $number, not card $connector_card_number"
    warn "the Mixxx port is VirMIDI $number-0. Enable the connector mapping on that port."
    warn "see section \"MIDI Connector\" in $configuration_runbook"
  fi
}

check_connector_card

resolve_command() {
  local command_name=$1
  local resolved
  resolved=$(command -v "$command_name" 2>/dev/null) \
    || die "$command_name is not executable; install musicindex-live-publisher first"
  printf '%s' "$resolved"
}

publisher_bin=$(resolve_command "$publisher_bin")
producer_bin=$(resolve_command "$producer_bin")

if [[ "$start_services" -eq 1 ]]; then
  command -v systemctl >/dev/null 2>&1 || die "systemctl is required to start user services"
  systemctl --user show-environment >/dev/null 2>&1 \
    || die "systemd user manager is not available; rerun with --no-start or start a user session"
fi

uid=$(id -u)
runtime_root=${XDG_RUNTIME_DIR:-/run/user/$uid}
config_home=${XDG_CONFIG_HOME:-$HOME/.config}
watch_dir=$runtime_root/musicindex-live-publisher/$instance/nowplaying
txt_file=$watch_dir/now-playing.txt
unit_dir=$config_home/systemd/user

case "$mode" in
  permanent)
    state_dir=$config_home/musicindex-live-publisher/$instance
    ;;
  temporary)
    state_dir=$runtime_root/musicindex-live-publisher-setup/$instance
    ;;
  *)
    die "unsupported mode: $mode"
    ;;
esac

config_file=$state_dir/config.toml
token_dir=$state_dir/tokens
token_file=$token_dir/$target.token
publisher_unit=$unit_dir/musicindex-live-publisher@$instance.service
producer_unit=$unit_dir/mixxx-now-playing.service
publisher_unit_name=musicindex-live-publisher@$instance.service
producer_unit_name=mixxx-now-playing.service
stamp=$(date -u '+%Y%m%dT%H%M%SZ')

reject_systemd_arg() {
  local name=$1
  local value=$2
  case "$value" in
    *[[:space:]]*|*%*)
      die "$name contains whitespace or %, which this simple generated unit does not escape: $value"
      ;;
  esac
}

for name in publisher_bin producer_bin config_file watch_dir txt_file; do
  reject_systemd_arg "$name" "${!name}"
done

toml_string() {
  local value=$1
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '"%s"' "$value"
}

file_has_marker() {
  local path=$1
  [[ -e "$path" ]] && grep -Fq "$generated_marker" "$path"
}

config_event_ids() {
  local path=$1
  sed -n 's/^[[:space:]]*event_id[[:space:]]*=[[:space:]]*"\([^"]*\)".*$/\1/p' "$path"
}

# Reserved safety task 003: the generated marker does not allow a replace. A
# config may be replaced without --force only when each event ID in it is the
# placeholder. A real event ID can be a reserved event with a one-time token.
config_has_only_placeholder() {
  local path=$1
  local ids
  local id
  ids=$(config_event_ids "$path") || return 1
  [[ -n "$ids" ]] || return 1
  while IFS= read -r id; do
    [[ "$id" == "$placeholder_event_id" ]] || return 1
  done <<< "$ids"
}

can_replace_config() {
  local path=$1
  [[ ! -e "$path" ]] && return 0
  config_has_only_placeholder "$path" && return 0
  [[ "$force" -eq 1 ]]
}

refuse_config() {
  local path=$1
  local ids
  ids=$(config_event_ids "$path" 2>/dev/null | tr '\n' ' ') || ids=
  ids=${ids% }
  printf '%s: refusing to replace existing config %s.\n' "$program" "$path" >&2
  if [[ -n "$ids" ]]; then
    printf '%s: The config names the event ID %s.\n' "$program" "$ids" >&2
  else
    printf '%s: The config names no event ID.\n' "$program" >&2
  fi
  printf '%s: No relay request ran. The config and the token did not change.\n' "$program" >&2
  printf '%s: To write only the two units, run again with --units-only.\n' "$program" >&2
  printf '%s: To back up the config and provision a new live item, run again with --force.\n' \
    "$program" >&2
  exit 1
}

can_replace_generated_file() {
  local path=$1
  [[ ! -e "$path" ]] && return 0
  file_has_marker "$path" && return 0
  [[ "$force" -eq 1 ]]
}

backup_file() {
  local path=$1
  [[ -e "$path" ]] || return 0
  local backup=$path.bak.$stamp
  cp -p "$path" "$backup"
  warn "backed up $path to $backup"
}

write_generated_file() {
  local path=$1
  local file_mode=$2
  local tmp
  tmp=$(mktemp "$path.tmp.XXXXXX")
  cat > "$tmp"
  chmod "$file_mode" "$tmp"
  mv "$tmp" "$path"
}

if [[ "$units_only" -eq 1 ]]; then
  # --units-only reads no token and writes no config and no token. It needs
  # the config that an earlier run wrote, because the units name it.
  [[ -e "$config_file" ]] \
    || die "--units-only needs an existing config, but $config_file does not exist. Run the script without --units-only first."
else
  install -d -m 0700 "$state_dir" "$token_dir"
  can_replace_config "$config_file" || refuse_config "$config_file"
fi
install -d -m 0755 "$unit_dir"

can_replace_generated_file "$publisher_unit" \
  || die "refusing to replace existing unit $publisher_unit; rerun with --force or edit it manually"
can_replace_generated_file "$producer_unit" \
  || die "refusing to replace existing unit $producer_unit; rerun with --force or edit it manually"

if [[ "$units_only" -eq 0 ]]; then
  # Reserved safety task 001 review: -e does not see a symbolic link that points
  # nowhere. Check -L too.
  if [[ -e "$token_file" || -L "$token_file" ]]; then
    [[ "$force" -eq 1 ]] \
      || die "refusing to replace existing token $token_file; rerun with --force to provision a new live item"
    mv "$token_file" "$token_file.bak.$stamp"
    warn "backed up $token_file to $token_file.bak.$stamp"
  fi

  printf 'Provisioning MusicIndex live item at %s...\n' "$endpoint"
  provision_output=$("$publisher_bin" provision \
    --endpoint "$endpoint" \
    --target "$target" \
    --token-file "$token_file")
  printf '%s\n' "$provision_output"
  event_id=$(printf '%s\n' "$provision_output" | sed -n 's/^event_id = "\(.*\)"$/\1/p' | tail -n 1)
  [[ -n "$event_id" ]] || die "could not parse event_id from provision output"

  backup_file "$config_file"
  {
    printf '%s\n' "$generated_marker"
    printf '# Mode: %s\n' "$mode"
    printf '# The %s unit overrides watch_dir with --watch-dir.\n' "$publisher_unit_name"
    printf 'watch_dir = %s\n' "$(toml_string "$watch_dir")"
    printf 'endpoint = %s\n' "$(toml_string "$endpoint")"
    printf '\n'
    printf '[[target]]\n'
    printf 'name = %s\n' "$(toml_string "$target")"
    printf 'event_id = %s\n' "$(toml_string "$event_id")"
    printf 'token_file = %s\n' "$(toml_string "$token_file")"
    printf '\n'
    printf '# The publisher uses a fixed dead block while idle or non-V4V (ADR 0005).\n'
    printf '# No configuration changes it.\n'
  } | write_generated_file "$config_file" 0600
fi

backup_file "$publisher_unit"
write_generated_file "$publisher_unit" 0644 <<EOF
$generated_marker
[Unit]
Description=MusicIndex live publisher for Mixxx
Documentation=file:///usr/share/doc/musicindex-live-publisher/musicindex-live-publisher-deploy.md
StartLimitIntervalSec=300
StartLimitBurst=5

[Service]
Type=simple
ExecStart=$publisher_bin --config $config_file --watch-dir $watch_dir
Restart=on-failure
RestartSec=5s

RuntimeDirectory=musicindex-live-publisher/$instance/nowplaying
RuntimeDirectoryMode=0700
RuntimeDirectoryPreserve=yes

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictSUIDSGID=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
UMask=0077

[Install]
WantedBy=default.target
EOF

backup_file "$producer_unit"
write_generated_file "$producer_unit" 0644 <<EOF
$generated_marker
[Unit]
Description=Mixxx now-playing producer for MusicIndex
Documentation=file:///usr/share/doc/musicindex-live-publisher/musicindex-live-publisher-deploy.md
Wants=$publisher_unit_name
After=$publisher_unit_name

[Service]
Type=simple
ExecStart=$producer_bin --format json --target $target --id3-file $watch_dir/$target.json --txt-file $txt_file
Restart=always
RestartSec=10s

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
PrivateTmp=true
RuntimeDirectory=musicindex-live-publisher/$instance/nowplaying
RuntimeDirectoryMode=0700
RuntimeDirectoryPreserve=yes
# ADR 0006: the producer opens the raw MIDI device of the V4V card in /dev/snd.
# A user service has only the device access of its user.
PrivateDevices=false
ProtectKernelTunables=true
ProtectKernelModules=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictSUIDSGID=true
LockPersonality=true

[Install]
WantedBy=default.target
EOF

if [[ "$units_only" -eq 1 ]]; then
  printf 'Config not changed: %s\n' "$config_file"
  printf 'Wrote unit: %s\n' "$publisher_unit"
  printf 'Wrote unit: %s\n' "$producer_unit"
else
  printf 'Wrote config: %s\n' "$config_file"
  printf 'Wrote token: %s\n' "$token_file"
  printf 'Wrote unit: %s\n' "$publisher_unit"
  printf 'Wrote unit: %s\n' "$producer_unit"
  printf 'Event ID: %s\n' "$event_id"
fi

mixxx_running=unknown
if command -v pgrep >/dev/null 2>&1; then
  if pgrep -x mixxx >/dev/null 2>&1 || pgrep -f '(^|/)mixxx([[:space:]]|$)' >/dev/null 2>&1; then
    mixxx_running=yes
  else
    mixxx_running=no
  fi
fi

if [[ "$start_services" -eq 1 ]]; then
  systemctl --user daemon-reload
  systemctl --user reset-failed "$publisher_unit_name" "$producer_unit_name" >/dev/null 2>&1 || true

  if [[ "$units_only" -eq 1 ]]; then
    systemctl --user restart "$publisher_unit_name" "$producer_unit_name"
  elif [[ "$mode" == permanent ]]; then
    systemctl --user enable --now "$publisher_unit_name" "$producer_unit_name"
  else
    systemctl --user start "$publisher_unit_name" "$producer_unit_name"
  fi

  sleep 1
  if ! systemctl --user is-active --quiet "$publisher_unit_name"; then
    systemctl --user --no-pager --full status "$publisher_unit_name" >&2 || true
    die "$publisher_unit_name did not become active"
  fi

  if [[ "$mixxx_running" == yes ]]; then
    sleep 1
    if ! systemctl --user is-active --quiet "$producer_unit_name"; then
      systemctl --user --no-pager --full status "$producer_unit_name" >&2 || true
      die "$producer_unit_name did not stay active while Mixxx is running"
    fi
  elif [[ "$mixxx_running" == no ]]; then
    warn "Mixxx is not running; $producer_unit_name will restart until Mixxx starts"
  else
    warn "could not check whether Mixxx is running because pgrep is unavailable"
  fi

  printf 'Started: %s\n' "$publisher_unit_name"
  printf 'Started: %s\n' "$producer_unit_name"
elif [[ "$units_only" -eq 1 ]]; then
  # --no-start runs no systemctl command, also with --units-only.
  printf 'Load and restart the units with:\n'
  printf '  systemctl --user daemon-reload\n'
  printf '  systemctl --user restart %s %s\n' "$publisher_unit_name" "$producer_unit_name"
else
  printf 'Start with:\n'
  if [[ "$mode" == permanent ]]; then
    printf '  systemctl --user enable --now %s %s\n' "$publisher_unit_name" "$producer_unit_name"
  else
    printf '  systemctl --user start %s %s\n' "$publisher_unit_name" "$producer_unit_name"
  fi
fi

if [[ "$mode" == temporary ]]; then
  warn "temporary mode uses runtime files under $runtime_root; rerun after logout or reboot"
  warn "generated user units remain in $unit_dir but are not enabled"
fi

printf 'Producer drop file: %s/%s.json\n' "$watch_dir" "$target"
printf 'Text metadata file: %s\n' "$txt_file"
